[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/share/*"
  to = "https://app.treklist.co/share/:splat"
  status = 302
  force = true
